<?php

namespace EnquisaBundle\Repository;

/**
 * OpcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpcionRepository extends \Doctrine\ORM\EntityRepository
{
}
