<?php

namespace EnquisaBundle\Repository;

/**
 * PreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOpciones()
    {
        return $this->createQueryBuilder('p')
            ->addSelect('o')
            ->join('p.opcions', 'o')
            ->orderBy('p.orde')
            ->getQuery()
            ->getArrayResult();
    }
}
