<?php

namespace EnquisaBundle\Repository;

/**
 * RespostaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespostaRepository extends \Doctrine\ORM\EntityRepository
{
}
