<?php

namespace EnquisaBundle\Repository;

/**
 * RestauranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestauranteRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getTotalRestaurantes()
    {        
        $dql =<<<DQL
SELECT count(restaurante.nome) AS total
FROM EnquisaBundle\Entity\Restaurante restaurante
DQL;

        $query = $this->getEntityManager()->createQuery($dql);
        $count = $query->getSingleScalarResult();
        
        return $count;
    }
    
}